---
- name: Update APT cache
  ansible.builtin.apt:
    update_cache: true
    cache_valid_time: 3600

- name: Install Squid
  ansible.builtin.apt:
    name:
      - squid
    state: present

- name: Stop Squid
  ansible.builtin.service:
    name: squid
    state: stopped
    enabled: false
