galaxy_info:
  namespace: tenminutevpn
  role_name: tenminutevpn

  author: Andrey Gubarev <account@andreygubarev.com> (andreygubarev.com)
  description: 10 Minute VPN
  company: andreygubarev

  license: MIT

  min_ansible_version: "9.0.0"

  platforms:
    - name: Debian
      versions:
        - bookworm

  galaxy_tags: []

dependencies: []
