---
dependency:
  name: galaxy
driver:
  name: molecule-qemu
platforms:
  - name: tenminutevpn
    image_url: https://cloud.debian.org/images/cloud/bullseye/latest/debian-11-genericcloud-arm64.qcow2
    image_checksum: sha512:https://cloud.debian.org/images/cloud/bullseye/latest/SHA512SUMS
provisioner:
  name: ansible
verifier:
  name: testinfra
