---
- name: Install Nginx
  hosts: default
  gather_facts: true
  become: true
  tasks:
    - name: Install the latest version of nginx
      ansible.builtin.apt:
        name: nginx
        state: present
        update_cache: true
