---
dependency:
  name: galaxy
driver:
  name: molecule-qemu
platforms:
  - name: tenminutevpn
    image_url: "${PACKER_IMAGE_URL}"
    image_checksum: "${PACKER_IMAGE_CHECKSUM}"
    image_arch: "${PACKER_IMAGE_ARCH}"
    image_format: raw
provisioner:
  name: ansible
verifier:
  name: testinfra
