name: Packer - Build

on:
  push:
    branches:
      - main
    tags:
      - "v*.*.*"

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install System Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -yq --no-install-recommends direnv
          sudo apt-get install -yq --no-install-recommends mkisofs qemu-system-x86 qemu-utils
          sudo chmod o+rwx /dev/kvm

      - name: Setup Packer
        uses: hashicorp/setup-packer@main
        with:
          version: "1.9.4"
