name: Packer - Release

on:
  push:
    branches:
      - main
    tags:
      - "v*.*.*"

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Setup Pipenv
        run: |
          python3.11 -m pip install --upgrade pipenv wheel

      - name: Configure Fast APT Mirror
        uses: vegardit/fast-apt-mirror.sh@v1

      - name: Install System Dependencies
        run: |
          sudo apt-get update && sudo apt-get install -yq --no-install-recommends \
            direnv \
            mkisofs \
            qemu-system-x86 \
            qemu-utils

      - name: Setup Packer
        uses: hashicorp/setup-packer@main
        with:
          version: "1.9.4"

      - name: Cache Python Virtual Environment
        uses: actions/cache@v3
        with:
          path: packer/.cache/venv
          key: ${{ runner.os }}-venv-${{ hashFiles('**/packer/Pipfile.lock') }}

      - name: Cache QEMU
        uses: actions/cache@v3
        with:
          path: packer/.cache/qemu
          key: ${{ runner.os }}-qemu-${{ hashFiles('**/packer/variables/*.pkrvars.hcl') }}

      - name: Build
        run: |
          cd packer
          direnv allow
          direnv exec . make clean install build-debian12

      - name: Upload artifact
        if: startsWith(github.ref, 'refs/tags/v')
        uses: actions/upload-artifact@v4
        with:
          name: image
          path: |
            packer/.cache/packer/image/*
            !packer/.cache/packer/image/*.raw

  release:
    runs-on: ubuntu-latest
    needs: build
    if: startsWith(github.ref, 'refs/tags/v')

    permissions:
      contents: write

    steps:
      - name: Check if pre-release
        id: prerelease
        run: |
          echo "prerelease=$(if [[ "${{ github.ref }}" == *"rc"* ]]; then echo "true"; else echo "false"; fi)" >> "$GITHUB_OUTPUT"

      - uses: actions/download-artifact@v4
        with:
          name: image

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          prerelease: ${{ steps.prerelease.outputs.prerelease }}
          generate_release_notes: true
          files: |
            SHA512SUMS
            *.raw.gz
