name: Packer - Release

on:
  push:
    branches:
      - main
    tags:
      - "v*.*.*"

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install System Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -yq --no-install-recommends direnv
          sudo apt-get install -yq --no-install-recommends mkisofs qemu-system-x86 qemu-utils

      - name: Setup Packer
        uses: hashicorp/setup-packer@main
        with:
          version: "1.9.4"

      - name: Build
        run: |
          cd packer
          direnv allow
          make clean install build-debian12

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: image
          path: |
            packer/out/image/*
            !packer/out/image/*.raw

  release:
    runs-on: ubuntu-latest
    needs: build
    if: startsWith(github.ref, 'refs/tags/v')

    permissions:
      contents: write

    steps:
      - name: Check if pre-release
        id: prerelease
        run: |
          echo "prerelease=$(if [[ "${{ github.ref }}" == *"rc"* ]]; then echo "true"; else echo "false"; fi)" >> "$GITHUB_OUTPUT"

      - uses: actions/download-artifact@v4
        with:
          name: image

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          prerelease: ${{ steps.prerelease.outputs.prerelease }}
          generate_release_notes: true
          files: |
            SHA512SUMS
            *.raw.gz
