name: Packer - Release

on:
  pull_request:
  push:
    branches:
      - main
    tags:
      - "v*.*.*"

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-22.04
    env:
      PACKER_VERSION: 1.9.4

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Setup Pipenv
        run: |
          python3.11 -m pip install --upgrade pipenv wheel

      - name: Configure Fast APT Mirror
        uses: vegardit/fast-apt-mirror.sh@v1

      - name: Install System Dependencies
        run: |
          sudo apt-get update && sudo apt-get install -yq --no-install-recommends \
            direnv \
            mkisofs \
            qemu-system-x86 \
            qemu-utils

      - name: Cache Packer
        id: packer-cache
        uses: actions/cache@v3
        with:
          path: /opt/hostedtoolcache/**/packer
          key: ${{ runner.os }}-packer-${{ env.PACKER_VERSION }}

      - name: Setup Packer
        if: steps.packer-cache.outputs.cache-hit != 'true'
        uses: hashicorp/setup-packer@main
        with:
          version: ${{ env.PACKER_VERSION }}

      - name: Cache Python Virtual Environment
        uses: actions/cache@v3
        with:
          path: .cache/venv
          key: ${{ runner.os }}-venv-${{ hashFiles('**/packer/Pipfile.lock') }}

      - name: Cache QEMU
        uses: actions/cache@v3
        with:
          path: .cache/qemu
          key: ${{ runner.os }}-qemu-${{ hashFiles('**/packer/variables/*.pkrvars.hcl') }}

      - name: Build
        run: |
          direnv allow
          direnv exec . make build

      - name: "Upload artifact - Image"
        if: startsWith(github.ref, 'refs/tags/v')
        uses: actions/upload-artifact@v4
        with:
          name: image
          path: |
            .cache/packer/image/*
            !.cache/packer/image/*.raw

      - name: "Upload artifact - Image Raw"
        uses: actions/upload-artifact@v4
        with:
          name: image_raw
          path: |
            .cache/packer/image/*.raw
            .cache/packer/image/SHA512SUMS

  test:
    runs-on: ubuntu-22.04
    needs: build

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Setup Pipenv
        run: |
          python3.11 -m pip install --upgrade pipenv wheel

      - name: Configure Fast APT Mirror
        uses: vegardit/fast-apt-mirror.sh@v1

      - name: Install System Dependencies
        run: |
          sudo apt-get update && sudo apt-get install -yq --no-install-recommends \
            direnv \
            mkisofs \
            qemu-system-x86 \
            qemu-utils

      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: image_raw
          path: .cache/packer/image

      - name: Verify
        run: |
          direnv allow
          direnv exec . make test

  release:
    runs-on: ubuntu-22.04
    needs: [build, test]
    if: startsWith(github.ref, 'refs/tags/v')

    permissions:
      contents: write

    steps:
      - name: Check if pre-release
        id: prerelease
        run: |
          echo "prerelease=$(if [[ "${{ github.ref }}" == *"rc"* ]]; then echo "true"; else echo "false"; fi)" >> "$GITHUB_OUTPUT"

      - uses: actions/download-artifact@v4
        with:
          name: image

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          prerelease: ${{ steps.prerelease.outputs.prerelease }}
          generate_release_notes: true
          files: |
            SHA512SUMS
            *.raw.gz
